### ISSUE TITLE
Use ❄️ instead of 🧊 | Better readability

### ISSUE THREAD

**Issue by sveinn19** [adameli22/adameli22#1]
https://github.com/adameli22/adameli22/blob/307e7de13a3702179abe92b607c4a670e54bfd9e/README.md?plain=1#L5-L7

**Comment by sveinn19** [comment]
Or use 🧊land :D

**Comment by sveinn19** [comment]
https://github.com/adameli22/adameli22/pull/2

**Comment by adameli22** [comment]
Merged. closing the issue
